# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64river.proto\x12\x05proto\"0\n\x0bRequestArgs\x12\x10\n\x08\x62rokerid\x18\x01 \x01(\r\x12\x0f\n\x07request\x18\x02 \x01(\t\"\x1e\n\x0eResponseResult\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\xb1\x03\n\x06\x44river\x12:\n\rGetDriverInfo\x12\x12.proto.RequestArgs\x1a\x15.proto.ResponseResult\x12\x36\n\tSetConfig\x12\x12.proto.RequestArgs\x1a\x15.proto.ResponseResult\x12\x32\n\x05Setup\x12\x12.proto.RequestArgs\x1a\x15.proto.ResponseResult\x12\x32\n\x05Start\x12\x12.proto.RequestArgs\x1a\x15.proto.ResponseResult\x12\x34\n\x07Restart\x12\x12.proto.RequestArgs\x1a\x15.proto.ResponseResult\x12\x31\n\x04Stop\x12\x12.proto.RequestArgs\x1a\x15.proto.ResponseResult\x12\x30\n\x03Get\x12\x12.proto.RequestArgs\x1a\x15.proto.ResponseResult\x12\x30\n\x03Set\x12\x12.proto.RequestArgs\x1a\x15.proto.ResponseResult2o\n\x06Report\x12\x31\n\x04Post\x12\x12.proto.RequestArgs\x1a\x15.proto.ResponseResult\x12\x32\n\x05State\x12\x12.proto.RequestArgs\x1a\x15.proto.ResponseResultB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./proto'
  _globals['_REQUESTARGS']._serialized_start=23
  _globals['_REQUESTARGS']._serialized_end=71
  _globals['_RESPONSERESULT']._serialized_start=73
  _globals['_RESPONSERESULT']._serialized_end=103
  _globals['_DRIVER']._serialized_start=106
  _globals['_DRIVER']._serialized_end=539
  _globals['_REPORT']._serialized_start=541
  _globals['_REPORT']._serialized_end=652
# @@protoc_insertion_point(module_scope)
